require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'medportal' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  target 'medportalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'medportal-tvOS' do
  # Pods for medportal-tvOS

  target 'medportal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
